"use client";
import { useMemo, useState } from "react";

const initialOrders=[{id:"#KM-1042",customer:"Aarav Sharma",date:"23 Sep 2026",items:"500g Walnuts",total:799,status:"Paid"},{id:"#KM-1041",customer:"Meera Singh",date:"23 Sep 2026",items:"1kg Walnuts",total:1399,status:"Processing"},{id:"#KM-1040",customer:"Rohan Thapa",date:"22 Sep 2026",items:"250g Walnuts",total:449,status:"Shipped"},{id:"#KM-1039",customer:"Ananya Das",date:"22 Sep 2026",items:"500g Walnuts",total:799,status:"Delivered"}];

export default function Admin(){
 const [orders,setOrders]=useState(initialOrders); const [tab,setTab]=useState("Overview");
 const revenue=orders.reduce((s,o)=>s+o.total,0); const [search,setSearch]=useState("");
 const filtered=useMemo(()=>orders.filter(o=>(o.id+o.customer+o.items).toLowerCase().includes(search.toLowerCase())),[orders,search]);
 return <div className="admin-shell"><aside className="admin-side"><div className="admin-logo">KASHUR<span>MEWA</span><small>ADMIN</small></div>{["Overview","Orders","Products","Customers","Inventory","Settings"].map(t=><button className={tab===t?"active":""} onClick={()=>setTab(t)} key={t}>{t}</button>)}<a href="/">← View storefront</a></aside>
 <main className="admin-main"><header className="admin-top"><div><p className="eyebrow">KASHURMEWA COMMERCE</p><h1>{tab}</h1></div><div className="admin-user">NC <span>Administrator</span></div></header>
 {tab==="Overview"&&<><div className="metrics"><Metric label="Gross sales" value={"₹"+revenue.toLocaleString("en-IN")} note="+12.4% this month"/><Metric label="Orders" value={orders.length.toString()} note="4 active records"/><Metric label="Avg. order" value={"₹"+Math.round(revenue/orders.length).toLocaleString("en-IN")} note="Across all orders"/><Metric label="Stock" value="842" note="Units available"/></div><section className="admin-card"><div className="card-head"><div><span>RECENT ORDERS</span><h2>Latest activity</h2></div><button onClick={()=>setTab("Orders")}>VIEW ALL →</button></div><OrderTable orders={orders.slice(0,4)}/></section><div className="admin-grid"><section className="admin-card"><span>TOP PRODUCT</span><h2>Kashmiri Walnuts</h2><p className="muted">500g remains the highest-volume pack.</p><div className="bar"><i style={{width:"72%"}}/></div><div className="split"><span>72% of units</span><b>500g</b></div></section><section className="admin-card"><span>LOW STOCK</span><h2>Inventory watch</h2><div className="stock-row"><span>250g</span><b>184</b></div><div className="stock-row"><span>500g</span><b>426</b></div><div className="stock-row warning"><span>1kg</span><b>32</b></div></section></div></>}
 {tab==="Orders"&&<section className="admin-card"><div className="card-head"><div><span>ORDER MANAGEMENT</span><h2>{orders.length} orders</h2></div><input className="search" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search orders..." /></div><OrderTable orders={filtered}/></section>}
 {tab==="Products"&&<section className="admin-card"><div className="card-head"><div><span>CATALOG</span><h2>Products</h2></div><button className="admin-action">+ ADD PRODUCT</button></div><div className="product-admin"><div><b>Kashmiri Walnuts</b><span>Signature · 3 variants</span></div><strong>Active</strong><button>Edit</button></div></section>}
 {tab!=="Overview"&&tab!=="Orders"&&tab!=="Products"&&<section className="admin-card placeholder"><span>{tab.toUpperCase()}</span><h2>Ready for your commerce data.</h2><p>Connect Supabase to make this section persistent and multi-user.</p></section>}
 </main></div>
}
function Metric({label,value,note}:{label:string;value:string;note:string}){return <div className="metric"><span>{label}</span><strong>{value}</strong><small>{note}</small></div>}
function OrderTable({orders}:{orders:any[]}){return <div className="orders"><div className="order-head"><span>ORDER</span><span>CUSTOMER</span><span>ITEM</span><span>TOTAL</span><span>STATUS</span></div>{orders.map(o=><div className="order-row" key={o.id}><b>{o.id}</b><span>{o.customer}</span><span>{o.items}</span><span>₹{o.total.toLocaleString("en-IN")}</span><em className={o.status.toLowerCase()}>{o.status}</em></div>)}</div>}
