"use client";
import { useEffect, useState } from "react";
import { supabase } from "../../lib/supabase";

type Variant={id:string;size:string;price_inr:number;stock:number};
type Product={id:string;name:string;active:boolean;variants:Variant[]};

export default function Admin(){
 const [tab,setTab]=useState("Overview"); const [product,setProduct]=useState<Product|null>(null); const [loading,setLoading]=useState(true); const [message,setMessage]=useState("");
 const load=async()=>{setLoading(true);const {data,error}=await supabase.from("km_products").select("id,name,active,km_product_variants(id,size,price_inr,stock)").eq("slug","kashmiri-walnuts").single();if(error)setMessage("Could not load catalogue.");else{const p=data as any;p.variants=(p.km_product_variants||[]).sort((a:Variant,b:Variant)=>a.price_inr-b.price_inr);setProduct(p)}setLoading(false)};
 useEffect(()=>{load()},[]);
 const updateVariant=async(id:string,field:"price_inr"|"stock",value:string)=>{const n=Number(value);if(!Number.isFinite(n)||n<0)return;const {error}=await supabase.from("km_product_variants").update({[field]:n}).eq("id",id);if(error)setMessage("Update failed. Product editing requires an authenticated admin policy.");else{setMessage("Saved.");load()}};
 return <div className="admin-shell"><aside className="admin-side"><div className="admin-logo">KASHUR<span>MEWA</span><small>ADMIN</small></div>{["Overview","Products","Inventory","Orders","Customers","Settings"].map(t=><button className={tab===t?"active":""} onClick={()=>setTab(t)} key={t}>{t}</button>)}<a href="/">← View storefront</a></aside>
 <main className="admin-main"><header className="admin-top"><div><p className="eyebrow">KASHURMEWA COMMERCE</p><h1>{tab}</h1></div><div className="admin-user">STORE <span>Management</span></div></header>
 {tab==="Overview"&&<><div className="metrics"><Metric label="Catalogue" value={product?"1 product":"—"} note="Live from Supabase"/><Metric label="Variants" value={product?String(product.variants.length):"—"} note="Database records"/><Metric label="Stock units" value={product?product.variants.reduce((n,v)=>n+v.stock,0).toLocaleString("en-IN"):"—"} note="Current inventory"/><Metric label="Pricing" value={product?"Live":"—"} note="No prices in code"/></div><section className="admin-card"><div className="card-head"><div><span>PRODUCT CATALOGUE</span><h2>{product?.name||"Loading..."}</h2></div><button onClick={()=>setTab("Products")}>MANAGE PRODUCT →</button></div>{product&&<div className="orders"><div className="order-head"><span>VARIANT</span><span>PRICE</span><span>STOCK</span><span>STATUS</span><span></span></div>{product.variants.map(v=><div className="order-row" key={v.id}><b>{v.size}</b><span>₹{Number(v.price_inr).toLocaleString("en-IN")}</span><span>{v.stock}</span><em className={v.stock>0?"delivered":"processing"}>{v.stock>0?"IN STOCK":"OUT OF STOCK"}</em><span>Live</span></div>)}</div>}</section></>}
 {tab==="Products"&&<section className="admin-card"><div className="card-head"><div><span>CATALOG</span><h2>Product pricing</h2></div><button onClick={load}>REFRESH</button></div>{loading?<p className="muted">Loading catalogue…</p>:product?.variants.map(v=><div className="product-admin" key={v.id}><div><b>{product.name}</b><span>{v.size} variant</span></div><label>₹ <input className="admin-input" type="number" min="0" value={v.price_inr} onChange={e=>setProduct({...product,variants:product.variants.map(x=>x.id===v.id?{...x,price_inr:Number(e.target.value)}:x)})} onBlur={e=>updateVariant(v.id,"price_inr",e.target.value)}/></label><label>Stock <input className="admin-input small" type="number" min="0" value={v.stock} onChange={e=>setProduct({...product,variants:product.variants.map(x=>x.id===v.id?{...x,stock:Number(e.target.value)}:x)})} onBlur={e=>updateVariant(v.id,"stock",e.target.value)}/></label></div>)}{message&&<p className="admin-message">{message}</p>}</section>}
 {tab==="Inventory"&&<section className="admin-card"><span>INVENTORY</span><h2>Live stock</h2>{product?.variants.map(v=><div className="stock-row" key={v.id}><span>{v.size}</span><b>{v.stock} units</b></div>)}</section>}
 {tab!=="Overview"&&tab!=="Products"&&tab!=="Inventory"&&<section className="admin-card placeholder"><span>{tab.toUpperCase()}</span><h2>Commerce data will appear here.</h2><p>Orders and customer records will be connected next.</p></section>}
 </main></div>
}
function Metric({label,value,note}:{label:string;value:string;note:string}){return <div className="metric"><span>{label}</span><strong>{value}</strong><small>{note}</small></div>}
