"use client";
import Link from "next/link";
import {useEffect,useState} from "react";
import {useRouter,useSearchParams} from "next/navigation";
import {supabase} from "../../lib/supabase";
export default function AccountPage(){
 const [mode,setMode]=useState("signin");const [email,setEmail]=useState("");const [password,setPassword]=useState("");const [busy,setBusy]=useState(false);const [message,setMessage]=useState("");const [signedIn,setSignedIn]=useState("");
 const router=useRouter();const search=useSearchParams();
 useEffect(()=>{supabase.auth.getSession().then(r=>setSignedIn(r.data.session?.user.email||""));const sub=supabase.auth.onAuthStateChange((_e,s)=>setSignedIn(s?.user.email||""));return()=>sub.data.subscription.unsubscribe()},[]);
 const submit=async(e:React.FormEvent)=>{e.preventDefault();setBusy(true);setMessage("");try{if(mode==="signup"){const r=await supabase.auth.signUp({email,password});if(r.error)throw r.error;setMessage("Check your email to confirm your account, then sign in.")}else{const r=await supabase.auth.signInWithPassword({email,password});if(r.error)throw r.error;router.push(search.get("next")||"/cart")}}catch(e){setMessage(e instanceof Error?e.message:"Could not complete account request.")}finally{setBusy(false)}};
 const signout=async()=>{await supabase.auth.signOut();setSignedIn("");setMessage("You are signed out.")};
 return <main className="account-shell"><header className="commerce-header"><Link className="logo" href="/">KASHUR<span>MEWA</span></Link><Link href="/shop">Continue shopping ↗</Link></header><section className="account-card"><span className="commerce-eyebrow">YOUR KASHURMEWA ACCOUNT</span>{signedIn?<><h1>Welcome<br/><i>back.</i></h1><p>{signedIn}</p><button className="detail-add" onClick={()=>router.push(search.get("next")||"/cart")}>CONTINUE ↗</button><button className="account-switch" onClick={signout}>Sign out</button></>:<><h1>{mode==="signin"?"Good to see":"Join us for"}<br/><i>{mode==="signin"?"you again.":"the good stuff."}</i></h1><p>Sign in or create an account to continue to checkout.</p><div className="account-tabs"><button className={mode==="signin"?"selected":""} onClick={()=>setMode("signin")}>SIGN IN</button><button className={mode==="signup"?"selected":""} onClick={()=>setMode("signup")}>CREATE ACCOUNT</button></div><form onSubmit={submit}><label>Email address<input type="email" autoComplete="email" required value={email} onChange={e=>setEmail(e.target.value)} placeholder="you@example.com"/></label><label>Password<input type="password" autoComplete={mode==="signin"?"current-password":"new-password"} minLength={6} required value={password} onChange={e=>setPassword(e.target.value)} placeholder="At least 6 characters"/></label><button className="detail-add" disabled={busy}>{busy?"PLEASE WAIT…":mode==="signin"?"SIGN IN ↗":"CREATE ACCOUNT ↗"}</button></form></>}{message&&<p className="account-message">{message}</p>}<Link className="account-back" href="/cart">← Return to your bag</Link></section><footer className="commerce-footer"><span>THE TASTE OF KASHMIR.</span><Link href="/shop">Shop walnuts</Link></footer></main>
}