"use client";
import Image from "next/image";
import Link from "next/link";
import { useEffect, useState } from "react";
import { supabase } from "../lib/supabase";

type Variant={id:string;size:string;price_inr:number;stock:number};
type Product={id:string;name:string;description:string;origin:string;ingredients:string;variants:Variant[];images:{url:string;alt_text:string|null;sort_order:number}[]};

export default function Home(){
 const [product,setProduct]=useState<Product|null>(null); const [size,setSize]=useState(""); const [cart,setCart]=useState(0); const [error,setError]=useState("");
 useEffect(()=>{(async()=>{const {data,error}=await supabase.from("km_products").select("id,name,description,origin,ingredients,km_product_variants(id,size,price_inr,stock),km_product_images(url,alt_text,sort_order)").eq("slug","kashmiri-walnuts").eq("active",true).single();if(error){setError("Product catalogue is temporarily unavailable.");return;}const p=data as any;p.variants=(p.km_product_variants||[]).sort((a:Variant,b:Variant)=>a.price_inr-b.price_inr);p.images=(p.km_product_images||[]).sort((a:any,b:any)=>a.sort_order-b.sort_order);setProduct(p);setSize(p.variants[0]?.size||"");try{const c=JSON.parse(localStorage.getItem("kashurmewa-cart")||"[]");setCart(c.reduce((n:number,i:{qty:number})=>n+i.qty,0))}catch{}})()},[]);
 const selected=product?.variants.find(v=>v.size===size);
 const addToBag=()=>{if(!selected)return;try{const current=JSON.parse(localStorage.getItem("kashurmewa-cart")||"[]");const existing=current.find((i:{size:string})=>i.size===selected.size);if(existing)existing.qty+=1;else current.push({productId:product.id,variantId:selected.id,qty:1});localStorage.setItem("kashurmewa-cart",JSON.stringify(current));setCart(current.reduce((n:number,i:{qty:number})=>n+i.qty,0));}catch{}};
 return <main>
 <div className="announcement">FREE PAN-INDIA DELIVERY ON ORDERS ABOVE ₹999</div>
 <header className="header"><Link className="brand" href="/">KASHUR<span>MEWA</span></Link><nav><a href="#shop">Shop</a><a href="#story">Our Story</a><a href="#origin">Kashmir</a><a href="#journal">Journal</a></nav><div className="actions"><button aria-label="Search">⌕</button><button aria-label="Account">♙</button><Link className="cart" href="/cart">Bag <b>{cart}</b></Link></div></header>
 <section className="hero"><div className="hero-copy"><p className="eyebrow">THE TASTE OF KASHMIR</p><h1>Walnuts from the<br/><em>valleys of Kashmir.</em></h1><p className="lead">A thoughtfully sourced selection of Kashmiri walnuts, packed to preserve their natural character and delivered to your door.</p><div className="hero-cta"><a className="button dark" href="#shop">SHOP WALNUTS <span>↗</span></a><span className="quiet">Naturally grown · Carefully packed</span></div></div><div className="hero-photo">{product?.images[0] ? <Image src={product.images[0].url} alt={product.images[0].alt_text || "Kashurmewa product"} fill priority sizes="(max-width: 800px) 100vw, 50vw"/> : <div className="image-placeholder">Upload product photography from administration.</div>}</div></section>
 <section className="strip"><span>ORIGIN</span><strong>{product?.origin||"KASHMIR, INDIA"}</strong><span>SELECTION</span><strong>PREMIUM WALNUTS</strong><span>DELIVERY</span><strong>PAN-INDIA</strong></section>
 <section id="shop" className="product-section"><div className="section-head"><div><p className="eyebrow">FROM THE VALLEY</p><h2>A walnut worth<br/><em>opening slowly.</em></h2></div><p>Simple ingredients. Honest sourcing. No unnecessary noise.</p></div>
 {error?<div className="catalog-error">{error}</div>:product?<div className="product-grid"><div className="product-image real-product-image">{product.images[1]?.url || product.images[0]?.url ? <Image src={product.images[1]?.url || product.images[0]?.url} alt={product.images[1]?.alt_text || product.images[0]?.alt_text || product.name} fill sizes="(max-width: 800px) 100vw, 50vw"/> : <div className="image-placeholder">Upload product photography from administration.</div>}<div className="image-caption">KASHMIRI WALNUTS</div></div><div className="product-info"><p className="eyebrow">01 / SIGNATURE</p><h3>{product.name}</h3><p className="description">{product.description}</p><div className="details"><div><span>Origin</span><b>{product.origin}</b></div><div><span>Ingredients</span><b>{product.ingredients}</b></div><div><span>Pack</span><b>Resealable</b></div></div><div className="size-row"><span>SELECT SIZE</span><div>{product.variants.map(v=><button key={v.id} disabled={v.stock===0} className={size===v.size?"selected":""} onClick={()=>setSize(v.size)}>{v.size}</button>)}</div></div><div className="buy"><strong>{selected?"₹"+Number(selected.price_inr).toLocaleString("en-IN"):"—"}</strong><button className="button dark" disabled={!selected||selected.stock===0} onClick={addToBag}>{selected?.stock===0?"OUT OF STOCK":"ADD TO BAG"} <span>+</span></button></div></div></div>:<div className="catalog-loading">Loading the harvest...</div>}
 </section>
 <section id="story" className="story"><div><p className="eyebrow">THE KASHURMEWA STORY</p><h2>From Kashmir,<br/><em>with care.</em></h2></div><div className="story-copy"><p>Kashurmewa is built around a simple idea: good food does not need to be complicated. We bring the character of Kashmir to the everyday table through carefully selected produce and considered packaging.</p><p>Every pack is prepared with attention to freshness, origin and the small details that make a pantry staple feel special.</p><a href="#origin">DISCOVER OUR APPROACH →</a></div></section>
 <section id="origin" className="origin"><div className="origin-image real-origin-image"><div className="origin-art"><span>THE VALLEY · KASHMIR</span><strong>Origin-led.</strong><small>Manage brand photography from administration.</small></div></div><div className="origin-copy"><p className="eyebrow">WHERE IT BEGINS</p><h2>The character of<br/><em>Kashmir.</em></h2><p>High valleys, cool seasons and generations of cultivation give Kashmiri walnuts their distinctive place in the pantry.</p><div className="origin-facts"><span><b>01</b> SOURCE WITH CARE</span><span><b>02</b> PACK FOR FRESHNESS</span><span><b>03</b> DELIVER WITH PURPOSE</span></div></div></section>
 <section id="journal" className="journal"><div className="section-head"><div><p className="eyebrow">FROM THE JOURNAL</p><h2>Notes from<br/><em>the valley.</em></h2></div></div><div className="journal-grid"><article><span>01 · ORIGIN</span><h3>What makes a Kashmiri walnut different?</h3><a href="#">READ NOTE →</a></article><article><span>02 · PANTRY</span><h3>A simple guide to storing walnuts well.</h3><a href="#">READ NOTE →</a></article><article><span>03 · KASHMIR</span><h3>Following the walnut season through the valley.</h3><a href="#">READ NOTE →</a></article></div></section>
 <footer><div className="footer-brand"><Link className="brand" href="/">KASHUR<span>MEWA</span></Link><p>The Taste of Kashmir.</p></div><div><span className="footer-title">SHOP</span><a href="#shop">Kashmiri Walnuts</a><Link href="/cart">Cart & Checkout</Link><a href="#">Contact</a></div><div><span className="footer-title">EXPLORE</span><a href="#story">Our Story</a><a href="#origin">Kashmir</a></div><div><span className="footer-title">NEWSLETTER</span><p>Occasional notes from Kashmir.</p><div className="email"><input placeholder="Your email address"/><button>→</button></div></div><div className="copyright">© 2026 KASHURMEWA · ALL RIGHTS RESERVED</div></footer>
 </main>;
}
