"use client";
import Link from "next/link";
import {useEffect,useState} from "react";
import {supabase} from "../../lib/supabase";
type V={id:string;size:string;price_inr:number;stock:number};
type P={id:string;name:string;slug:string;description:string;km_product_variants:V[];km_product_images:{url:string;sort_order:number}[]};
export default function ShopPage(){
 const [items,setItems]=useState<P[]>([]);const [q,setQ]=useState("");const [sort,setSort]=useState("featured");const [loading,setLoading]=useState(true);
 useEffect(()=>{(async()=>{const r=await supabase.from("km_products").select("id,name,slug,description,km_product_variants(id,size,price_inr,stock),km_product_images(url,sort_order)").eq("active",true);setItems((r.data||[]) as P[]);setLoading(false)})()},[]);
 const filtered=items.filter(p=>p.name.toLowerCase().includes(q.toLowerCase())).sort((a,b)=>sort==="low"?Math.min(...a.km_product_variants.map(v=>v.price_inr))-Math.min(...b.km_product_variants.map(v=>v.price_inr)):sort==="high"?Math.min(...b.km_product_variants.map(v=>v.price_inr))-Math.min(...a.km_product_variants.map(v=>v.price_inr)):0);
 return <main className="commerce-page"><header className="commerce-header"><Link className="logo" href="/">KASHUR<span>MEWA</span></Link><nav><Link className="active" href="/shop">Shop</Link><Link href="/#story">Our story</Link><Link href="/account">Account</Link></nav><Link className="commerce-bag" href="/cart">Bag ↗</Link></header>
 <section className="shop-banner"><div><span className="commerce-eyebrow">THE KASHURMEWA SHOP</span><h1>Good things<br/><i>start here.</i></h1><p>Thoughtfully selected Kashmiri walnuts, packed for your everyday table.</p></div><div className="shop-banner-image"><img src="https://images.pexels.com/photos/8303558/pexels-photo-8303558.jpeg" alt="Walnuts arranged on a natural surface"/></div></section>
 <section className="catalogue"><div className="catalogue-top"><div><span className="commerce-eyebrow">THE PANTRY EDIT</span><h2>Shop walnuts</h2></div><div className="catalogue-controls"><input placeholder="Search the shop…" aria-label="Search products" value={q} onChange={e=>setQ(e.target.value)}/><select aria-label="Sort products" value={sort} onChange={e=>setSort(e.target.value)}><option value="featured">Featured</option><option value="low">Price: low to high</option><option value="high">Price: high to low</option></select></div></div>
 {loading?<p className="commerce-muted">Loading collection…</p>:!filtered.length?<p className="commerce-muted">No products match your search.</p>:<div className="commerce-grid">{filtered.map(p=>{const vs=[...p.km_product_variants].sort((a,b)=>a.price_inr-b.price_inr);const image=[...p.km_product_images].sort((a,b)=>a.sort_order-b.sort_order)[0]?.url||"https://images.pexels.com/photos/8303558/pexels-photo-8303558.jpeg";return <Link className="commerce-product" href={"/products/"+p.slug} key={p.id}><div className="commerce-product-image"><img src={image} alt={p.name}/><span>EXPLORE ↗</span></div><div className="commerce-product-info"><div><small>KASHURMEWA SIGNATURE</small><h3>{p.name}</h3><p>{vs.map(v=>v.size).join(" · ")}</p></div><strong>From ₹{vs.length?Math.min(...vs.map(v=>v.price_inr)).toLocaleString("en-IN"):"—"}</strong></div></Link>})}</div>}</section>
 <footer className="commerce-footer"><Link className="logo" href="/">KASHUR<span>MEWA</span></Link><span>The Taste of Kashmir.</span><Link href="/account">Your account</Link><Link href="/cart">Your bag</Link></footer></main>
}